### ISSUE TITLE
Copy magnet link

### ISSUE THREAD

**Issue by CarlosVelasco** [leonsoft-kras/transmisson-remote-gui#911]
I have installed latest version but I can't see any way to copy magnet link of a torrent.
Is this implemented? I have seen other transmission web alternatives, like Shift, that have the option.

**Comment by leonsoft-kras** [comment]
![default](https://cloud.githubusercontent.com/assets/11468577/15288689/c7d26282-1b96-11e6-9e93-31cee638b619.png)

**Comment by CarlosVelasco** [comment]
No, I don't mean adding, I mean "retrieving" from a current torrent already added

**Comment by leonsoft-kras** [comment]
This function is not here

**Comment by Sushubh** [comment]
Came here to file a feature request for the same. Ability to copy magnet links for the existing torrents would be nice to have. Please consider it. Thanks!

**Comment by Revertron** [comment]
Yes, I think it will be a handy feature too.

**Comment by antekgla** [comment]
@leonsoft-kras actually the Transmission core has this function as a field more of the torrent info.
From **RpcObj.RPCVersion >= 7** there is a new arg "magnetLink"

If in **rpc.pas** line 506 

`  args:=FRpc.RequestInfo(TorrentId, ['totalSize', 'sizeWhenDone', 'leftUntilDone', 'pieceCount', 'pieceSize', 'haveValid', 'hashString', 'comment', 'downloadedEver', 'uploadedEver', 'corruptEver', 'errorString',
'announceResponse', 'downloadLimit', 'downloadLimitMode', 'uploadLimit', 'uploadLimitMode',
'maxConnectedPeers', 'nextAnnounceTime', 'dateCreated', 'creator', 'eta', 'peersSendingToUs', 'seeders','peersGettingFromUs','leechers', 'uploadRatio', 'addedDate', 'doneDate', 'activityDate', 'downloadLimited', 'uploadLimited', 'downloadDir', 'id', 'pieces', 'trackerStats', 'secondsDownloading', 'secondsSeeding']);
`

you add a field **'magnetLink'** at the end:

`  args:=FRpc.RequestInfo(TorrentId, ['totalSize', 'sizeWhenDone', 'leftUntilDone', 'pieceCount', 'pieceSize', 'haveValid', 'hashString', 'comment', 'downloadedEver', 'uploadedEver', 'corruptEver', 'errorString', 'announceResponse', 'downloadLimit', 'downloadLimitMode', 'uploadLimit', 'uploadLimitMode', 'maxConnectedPeers', 'nextAnnounceTime', 'dateCreated', 'creator', 'eta', 'peersSendingToUs',
'seeders','peersGettingFromUs','leechers', 'uploadRatio', 'addedDate', 'doneDate', 'activityDate', 'downloadLimited', 'uploadLimited', 'downloadDir', 'id', 'pieces', 'trackerStats', 'secondsDownloading', 'secondsSeeding', 'magnetLink']);
`

you easily could use this new field as a caption for a new label (txMagnetLink) in the Torrent Info of General Tab adding a line in the **procedure TMainForm.FillGeneralInfo(t: TJSONObject);** like this

`txMagnetLink.Caption:= t.Strings['magnetLink'];`


![magnetlabel](https://cloud.githubusercontent.com/assets/24402722/21536927/1d8a49e6-cd68-11e6-9dab-04908fb09735.jpg)

from there with a right click you could copy the magnet link to to clipboard.

_Note to users: If @leonsoft-kras implement this, be careful sharing this magnets links because in a private tracker you could reveal to other people your personal passkey (opening the door to someone to trash your ratio)._

**Comment by leonsoft-kras** [comment]
many thanks!
I will try to implement it in the near future. :)

**Comment by CarlosVelasco** [comment]
Could you put an option in the Torrent menu or Context menu (right click) to copy the magnet link? Would be very useful.
There is also a minor cosmetic bug, the magnetic link is not aligned to "Added on" or "hash", it appears displaced one space to the right.

**Comment by leonsoft-kras** [comment]
1. I do not quite understand your proposal. Now it is necessary to highlight the entire magnet link and copy it to the clipboard.
2. The control itself is aligned with the horizontal.

Changing form (Issue 1 and 2) has caused some problems. To save time is realized in this way.

**Comment by CarlosVelasco** [comment]
1. I mean to put a new option in the Torrent menu to automatically copy magnet link to clipboard for current selected torrent.
Yes, right now we can select all the magnet and copy, but this would be really better.
![magnet menu](https://cloud.githubusercontent.com/assets/5107748/21581298/2d312fec-d02c-11e6-98b7-288dab8226b7.jpg)

2. I see a gap (note that a I am using Scaling 125% in Windows):
![magnet gap](https://cloud.githubusercontent.com/assets/5107748/21581299/339f4c42-d02c-11e6-8646-43f9611aaefc.jpg)

**Comment by leonsoft-kras** [comment]
1. It makes no sense to automatically copy the link to the clipboard. Now the program detects the magnet links in the clipboard. As a result, people will always see a dialog for entering a new torrent.

2. I know about the small displacement. But in the form of control is positioned correctly. Then while working something goes wrong.

**Comment by antekgla** [comment]
**leonsoft-kras**
>Changing form (Issue 1 and 2) has caused some problems. To save time is realized in this way.

This is true. I have some problems at implementing too, because if you add a new Label as others fields of the torrent the Autosize property of the label is always true (even if you manually put to false) and the widht of the panel change dramatically. I don't know because your TEdit resizes also but not to the full extension of the text of magnet link. This is not the behavior of my label.
I dont was able to solve this other what add a new panel only for the magnet link label.
But it is no good also because screws the alignment with other labels.
The original programmer make use of ChildSizing.Layout property of controls what makes this very hard. 

But @leonsoft-kras you could assign the PopUpMenu --> pmLabels to your TEdit to make easy to copy the link, without need of select the text of magnet link. However you have to assigning it manually thru the Object Inspector in Lazarus because the original author assigns this menu in code to all the labels in the procedure ClearChilder inside of procedure ClearDetailsInfo but **only** if the control is a label. The guy is very smart at coding this app.

**Comment by leonsoft-kras** [comment]
I will try to improve this function. I wrote a very long time in Pascal. The last 18 years I write in С/С++/С#. Therefore, to understand sometimes is not easy.

**Comment by antekgla** [comment]
Well I think what I achieve a solution what would make everybody happy 😄 
@CarlosVelasco the copy magnet link would be part of the torrent popmenu as you want it.
@leonsoft-kras now we could remove the new labels/edit for magnet link what trashed the alignment of the others labels.
I think what this solution is better also because allow to copy **one** or **several** magnet links to the clipboard based in your current selection in the torrent list.
So if you adopt my solution you could remove the changes in **rpc.pas** line 506 and remove the new labels/edit for magnet links.

This is my solution:

- Make a new menu in PopUpMenu of torrents (**pmTorrents**) I made it below **Verify**. 
Lazarus autoname this item _MenuItem101_. The Caption is: **Copy Magnet Link(s)**

![menu magnet](https://cloud.githubusercontent.com/assets/24402722/21591654/eef3bbfa-d0e4-11e6-83f7-314c5b02d7b5.jpg)

- Make this code for the OnClick event of the new MenuItem

 ~~~~
procedure TMainForm.MenuItem101Click(Sender: TObject);
var
  req, args, tt: TJSONObject;
  ids, t: TJSONArray;
  i: Integer;
  TorrentIds: Variant;
  Magnets: TStringList;
begin
   TorrentIds:=GetSelectedTorrents;
   req:=TJSONObject.Create;
   args:=TJSONObject.Create;
   Magnets:=TStringList.Create;
try
       req.Add('method', 'torrent-get');
       ids:=TJSONArray.Create;
       for i:=VarArrayLowBound(TorrentIds, 1) to VarArrayHighBound(TorrentIds, 1) do
         ids.Add(integer(TorrentIds[i]));
       args.Add('ids', ids);
       args.Add('fields', TJSONArray.Create(['magnetLink']));
       req.Add('arguments', args);
       args:=RpcObj.SendRequest(req);
       if args = nil then begin
         CheckStatus(False);
         exit;
       end;
       t:=TJSONArray.Create;
       t:=args.Arrays['torrents'];
       for i:= 0 to t.Count-1 do
         begin
           tt:=t.Objects[i] as TJSONObject;
           Magnets.add(tt.Strings['magnetLink']);
         end;
       FLastClipboardLink := Magnets.Text;   // To Avoid TransGUI detect again this existing links
       Clipboard.AsText := Magnets.Text;
  finally
       req.Free;
       args.Free;
       Magnets.Free;
   end;
end;
~~~~

I added a line to avoid what TransGUI detect again this existing links in case you have checked this feature of monitoring the clipboard for torrent links.

- Make this new Menu Item available **only** if Transmission Core support it. This is made adding a line in **procedure TMainForm.UpdateUIRpcVersion(RpcVersion: integer);**

 ~~~~ 
MenuItem101.Visible:=RPCVersion >= 7; 
~~~~


That's all.
I hope what this work for you, I tested it and work OK for me.
Cheers! 👋
