### ISSUE TITLE
Set data location on linux with an annoying browse button in the middle

### ISSUE THREAD

**Issue by DiWa51** [leonsoft-kras/transmisson-remote-gui#943]
Hi,
Under Linux (mint) with 5.6.0 (but was the case with previous versions too), when I set data location for a torrent, I have a popup to set the new path. Though this path is overridden by a 'browse' button in the middle.
Somewhat annoying.

Please see the screenshot
![set-data-location](https://cloud.githubusercontent.com/assets/13403672/25592203/304716b6-2eb8-11e7-8c3d-57f92c3bfc6b.png)

**Comment by antekgla** [comment]
Maybe @Snegohod could have a answer to this because he is the provider of linux binaries.

Maybe he could check his **movetorrent.lfm** file to view if the btBrowse button is moved or have the Align property different to _alNone_

Sadly I not be able to reproduce this problem in Windows, the Browse button appears to the right in his place.

**Comment by leonsoft-kras** [comment]
I know about it. I'll see in the next few days.

**Comment by leonsoft-kras** [comment]
Somehow corrected a little. Try it.
I have a version in Windows and Linux now correctly display the button.

**Comment by DiWa51** [comment]
Hi
I'd be happy to test it if need be, though do you have a binary for me please?
Cheers

**Comment by DiWa51** [comment]
Way better! 
Thanks a lot @leonsoft-kras
